# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: Testando o Ansible
  displayName: 'Run a one-line script'

- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    inventoriesAgentMachine: 'noInventory'

  tasks:
  - name: "EXEMPLO DE REGISTER"
    shell: "date -u"
    register: linux_date

  - name: "EXIBINDO REGISTER"
    debug:
      msg: "{{ linux_date.start }}"